#!/usr/bin/env python
"""
    small script to check for unread count on imap inbox
"""
import imaplib

IMAPSERVER = 'imap.gmx.net'

USER = 'simon_ziegler@gmx.de'
PASSWORD = '"&*ZIEzX@2f6Y{YKNh'

mail = imaplib.IMAP4_SSL(IMAPSERVER)
mail.login(USER, PASSWORD)
mail.select("INBOX", True) # connect to inbox.
return_code, mail_ids = mail.search(None, 'UnSeen')
if mail_ids[0] == "":
   	count1 = 0;
else:
    count1 = len(mail_ids[0].split(" "))
    
IMAPSERVER = 'mail.hs-fulda.de'
    
USER = 'simon-thomas.ziegler@informatik.hs-fulda.de'
PASSWORD = 'l]Q)hy/wO?9\.%)KCv'

mail = imaplib.IMAP4_SSL(IMAPSERVER)
mail.login(USER, PASSWORD)
mail.select("INBOX", True) # connect to inbox.
return_code, mail_ids = mail.search(None, 'UnSeen')
if mail_ids[0] == "":
   	count2 = 0;
else:
    count2 = len(mail_ids[0].split(" "))
    

unread = count1 + count2

print unread
