#!/bin/bash

# Add a button to toggle play and pause on Spotify if it's running
if [[ $(ps -U root -u root -N | grep -Fo 'spotify') == *spotify* ]]; then
        STATUS=`playerctl -p spotify status`
        # Change the symbol based on if it's currently playing or paused:
        if [[ $STATUS == 'Paused' ]]; then
                playerctl play
        elif [[ $STATUS == 'Playing' ]]; then
                playerctl pause
	fi
else
	playerctl play-pause
fi
